main/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import TemplateView, DetailView
from .views import (ContactUsView, ProductListView, RegisterView,
    logout_user, add_to_cart, show_bestseller, BreweryListView, add_review,user_recommend_list,
    account_settings, manage_cart, remove_one_from_cart, add_one_to_cart,
    review_detail, review_list, show_brewery, UserProfileView,remove_product_from_cart, PostDetailView, PostListView)

from .models.product import Product
from main import forms, views, endpoints
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("about-us/",TemplateView.as_view(template_name="about_us.html"),name='about-us'),
    path('contact-us/', ContactUsView.as_view(),name='contact-us'),
    path('', show_bestseller,name='home'),
    path('add_to_cart/', add_to_cart, name='add-to-cart'),
    path('cart/', manage_cart, name='cart'),
    path('remove/<slug:slug>', remove_product_from_cart, name='remove-product-from-cart' ),
    path('add_one_to_cart/<slug:slug>', add_one_to_cart, name='add-one-to-cart' ),
    path('remove_one_from_cart/<slug:slug>', remove_one_from_cart, name='remove-one-from-cart' ),
    path('brewery/<slug:brewery_slug>/', show_brewery, name='brewery'),
    path('breweries/', BreweryListView.as_view(), name='breweries'),
    path('product/<slug:slug>/', DetailView.as_view(model=Product), name='product'),
    path('products/<slug:tag>/', ProductListView.as_view(), name='product-list'),
    path('register/', RegisterView.as_view(), name='register'),
    path("login/", auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name="login.html", form_class=forms.AuthenticationForm), name="login",),
    path('logout/', logout_user, name='logout'),
    path('user/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('settings/', account_settings, name='settings'),
    path(
            "address/",
            views.AddressListView.as_view(),
            name="address_list",
    ), path(
           "address/create/",
            views.AddressCreateView.as_view(),
            name="address_create",
    ), path(
           "address/<int:pk>/",
           views.AddressUpdateView.as_view(),
           name="address_update",
    ), path(
           "address/<int:pk>/delete/",
           views.AddressDeleteView.as_view(),
           name="address_delete",
    ),
    path("order/done/", TemplateView.as_view(template_name="main/order_done.html"), name="checkout_done",),
    path("order/address_select/",views.AddressSelectionView.as_view(),name="address_select",),
    path('order-dashboard', views.OrderView.as_view(), name='order_dashboard'),
    path('reviews/<int:id>', review_detail, name='review_detail'),
    path('reviews/',review_list,name='review_list'),

    path('product/<slug:slug>/add_review/', add_review, name='add_review'),
    path('recommendations/', user_recommend_list, name='user_recommend_list'),
    path('news/', PostListView.as_view(), name='news_list'),
    path('news/<int:pk>/', PostDetailView.as_view(), name='news_post'),



]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saketime_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from main import endpoints

router = routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)

"""saketime_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('main.urls')),
    path("",include('rest_framework.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models/address.py
from django.contrib.auth import get_user_model
from django.db import models


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
        ("jp", "Japan"),
        ("id", "Indonesia"),
    )

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP or Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return ", ".join(
        [
            self.name,
            self.address1,
            self.address2,
            self.zip_code,
            self.city,
            self.country,
        ])

main/models/post.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from cloudinary.models import CloudinaryField
from main.models import UserProfile

class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    lede = models.CharField(max_length=200, blank=True,null=True)
    date = models.DateTimeField(blank=True,null=True)
    image = CloudinaryField('image')
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

main/models/product.py
from django.db import models
from django.shortcuts import reverse
# Create your models here.
from django.utils.text import slugify
from .brewery import Brewery
from cloudinary.models import CloudinaryField
import numpy as np

SAKE_TYPES = (
    ('jd','Junmai Daiginjo'),
('d','Daiginjo'),
('jg','Junmai Ginjo'),
('g', 'Ginjo'),
('j','Junmai'),
('h','Honjozo'),
    ('f','Futsu'),
    ('o','Other'),
)


class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class ProductTag(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def natural_key(self):
        return (self.slug,)

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def active(self):
        return self.filter(active=True)

    def in_stock(self):
        return self.filter(in_stock=True)

    def get_by_natural_key(self, slug):
        return self.get(slug=slug),



class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True,null=True)
    short_description = models.TextField(blank=True,null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2,blank=True,null=True)
    slug = models.SlugField(max_length=100,null=True)
    active = models.BooleanField(default=True,blank=True,null=True)
    in_stock = models.BooleanField(default=True,blank=True,null=True)
    date_updated = models.DateTimeField(auto_now=True,null=True)
    average_rating = models.FloatField(default=0, null=True,blank=True)
    abv = models.FloatField(default=0,blank=True,null=True)
    tags = models.ManyToManyField(ProductTag, blank=True)
    sake_type = models.CharField(max_length=3, choices=SAKE_TYPES)
    brewery = models.ForeignKey(Brewery, null=True, blank=True, on_delete=models.CASCADE, related_name='products')
    volume = models.PositiveIntegerField(blank=True, null=True)
    units_sold = models.PositiveIntegerField(blank=True,null=True,default=0)

    objects = ProductManager()

    def average_rating(self):
        if self.reviews.all():
            all_ratings = map(lambda x:x.rating, self.reviews.all())
            return np.mean(list(all_ratings))
        else:
            return None

    def review_amount(self):
        if self.reviews.exists():
            return self.reviews.count()
        else:
            return 0

    def get_absolute_url(self):
        return reverse('product', kwargs={'slug':self.slug})

    def natural_key(self):
        return (self.slug,)

    def image_all(self):
        return self.images.all()

    def first_image(self):
        return self.images.first()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    # def get_add_to_cart_url(self):
    #     return reverse('add-to-cart', kwargs={
    #         'slug': self.slug
    #     })




class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = CloudinaryField('image')

    def __str__(self):
        return self.product.name

main/views/address.py
from django.views.generic.list import ListView
from main.models import Address
import logging
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView,UpdateView, DeleteView, FormView
from main.forms import AddressSelectionForm

# Create your views here.
logger = logging.getLogger(__name__)


class AddressListView(ListView):
    model = Address

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country", ]
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = Address
    fields = [
            "name",
            "address1",
            "address2",
            "zip_code",
            "city",
            "country",
        ]
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name = 'main/address_select.html'
    form_class = AddressSelectionForm
    success_url = reverse_lazy('checkout_done')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user']= self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session['cart_id']
        cart = self.request.cart
        cart.create_order(
            form.cleaned_data['billing_address'],
            form.cleaned_data['shipping_address']
        )

        return super().form_valid(form)

main/views/brewery.py
from django.shortcuts import render, redirect, render_to_response
from main.models import Brewery, Product
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from django.contrib import messages

def show_brewery(request, brewery_slug):

    context = {}

    try:

        brewery = Brewery.objects.get(slug=brewery_slug)

        products = Product.objects.filter(brewery__slug=brewery_slug)

        page = request.GET.get('page', 1)
        paginator = Paginator(products, 4)
        pages= paginator.page(page)

        context['brewery'] = brewery
        context['products'] = products
        context['page_obj'] = pages

        coords = {'lat': brewery.lat, 'long': brewery.long}



    except Brewery.DoesNotExist:
        context['brewery'] = None
        messages.error(request, 'That brewery does not exist')

    return render(request, 'main/brewery_page.html', context=context)


class BreweryListView(ListView):
    template_name = "main/brewery_list.html"
    paginate_by = 5

    def get_queryset(self):
        breweries = Brewery.objects.all()

        return breweries.order_by('prefecture')

main/views/cart.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from main.models import Product, Cart, CartLine
from main.forms import CartLineFormSet
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView


def add_to_cart(request):
    product = get_object_or_404(
        Product, id=request.GET.get("product")
    )
    cart = request.cart
    if not request.cart:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        cart = Cart.objects.create(user=user)
        request.session["cart_id"] = cart.id

    cartline, created = CartLine.objects.get_or_create(
        cart=cart, product=product
    )
    if not created:
        cartline.quantity += 1
        cartline.save()
    return HttpResponseRedirect(
        reverse("product", args=(product.slug,))
    )


def manage_cart(request):

    if not request.cart:
        return render(request, 'cart.html', {'formset':None})


    if request.method == 'POST':
        formset = CartLineFormSet(
            request.POST, instance=request.cart, prefix='cartline'
        )

        if formset.is_valid():

            formset.save()
    else:
        formset = CartLineFormSet(
            instance=request.cart
        )
    if request.cart.is_empty():
        return render(request, 'cart.html', {'formset': None})
    return render(request, 'cart.html', {'formset':formset})


def add_one_to_cart(request,slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.cart
    cartline = CartLine.objects.get(cart=cart, product=product)

    if cartline:
        cartline.quantity +=1
        cartline.save()
        cart.save()

    return redirect('cart')


def remove_one_from_cart(request,slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.cart
    cartline = CartLine.objects.get(product=product, cart=cart)

    if cartline and cartline.quantity>1:
        cartline.quantity -=1
        cartline.save()
        cart.save()
    else:
        cartline.delete()
        cart.save()


    return redirect('cart')


def remove_product_from_cart(request,slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.cart
    cartline = CartLine.objects.filter(product=product, cart=cart)

    if cartline:
        cartline.delete()

    return redirect('cart')







# class CartLineDeleteView(DeleteView):
#     model = CartLine
#     success_url = reverse_lazy('cart')
#
#     def get_queryset(self):
#         return self.model.objects.filter(cart__user=self.request.user)

main/views/contact.py
from django.views.generic.edit import FormView
from main import forms
import logging
logger = logging.getLogger(__name__)


class ContactUsView(FormView):
    form_class = forms.ContactForm
    template_name = 'contact_us.html'
    success_url = '/'

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

main/views/homepage.py
from django.shortcuts import render, redirect, render_to_response
from main.models import Brewery, Product


def show_bestseller(request):
    context ={}
    breweries = Brewery.objects.all()
    products = Product.objects.order_by('units_sold')
    context['best_product'] = products[0]

    most_sales = 0
    bestseller = None

    for brewery in breweries:
        most_sales = max(most_sales, brewery.get_total_sales())

    for brewery in breweries:
        if brewery.get_total_sales() == most_sales:
            bestseller = brewery
            context['best_brewery'] = bestseller

    return render(request, 'home.html', context)

main/views/logout.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib import messages


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out')
    return redirect('home')

main/views/news.py
from django.shortcuts import render
from main.models import Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class PostListView(ListView):
    model = Post
    template_name = 'news/news_list.html'

class PostDetailView(DetailView):
    model = Post
    template_name = 'news/news_post.html'

main/templates/main/address_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
<h2>Delete address</h2> <form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete it?</p>
<button type="submit" class="btn btn-danger">Submit </button>
</form>
    </div>
{% endblock content %}

main/templates/main/address_delete.html
{% extends "base.html" %}
{% block content %}
<h2>Delete address</h2> <form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete it?</p>
<button type="submit" class="btn btn-primary">Submit </button>
</form>
{% endblock content %}

main/templates/main/address_form.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <h2 class="my-3">Add a new address</h2>
        <div class="row">
            <div class="col-12 mb-4">
    <form method="POST" class="card-body">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-danger">Submit</button>
</form>
                </div>
            </div>
    </div>
{% endblock content %}

main/templates/main/address_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
<h4>List of your addresses</h4>
    <div class="row my-3">
 {% for address in object_list %}
<div class="col-auto">
    {{ address.name }} </br>
    {{ address.address1 }} </br>
{{ address.address2 }} </br>
{{ address.city }} </br>
{{ address.get_country_display }} </br>
<p>
<a href="{% url "address_update" address.id %}">Update
address</a> </p>
<p>
<a href="{% url "address_delete" address.id %}">Delete address</a>
</p>
</div>
   {% endfor %}



    </div>
<hr>
<a class="btn btn-danger" href="{% url "address_create" %}">Add new address</a>
    <a class="btn btn-danger" href="{% url "cart" %}">Back to cart</a>

    </div>
{% endblock content %}

main/templates/main/address_select.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
<h2>Select the billing/shipping addresses</h2>
        <form method="POST">
    {%  csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Submit</button>
    <a class="btn btn-danger" href="{% url "address_create" %}">Add a new one</a>
</form>
    </div>
{% endblock content %}

main/templates/main/address_update.html
{% extends "base.html" %}
{% block content %}

    <div class="container">
<h2>Add a new address</h2> <form method="POST">
{% csrf_token %}
{{ form.as_p }}
<button type="submit" class="btn btn-danger">Submit</button>
</form>
    </div>
{% endblock content %}

main/templates/main/brewery_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-5 text-center">
    <div class="row">
        {% for brewery in page_obj %}
        <div class="col">
<p>

        <img src="{{ brewery.image.url }}" height="200" width="200"/>
        </p>
        <p><a href="{% url 'brewery' brewery.slug%}"> {{ brewery.name }}</a></p>
        Prefecture: {{ brewery.prefecture }}
        </div>
        {% endfor %}

    </div>



    </div>







{% endblock content %}

main/templates/main/brewery_page.html
{% extends 'base.html' %}
{% block content %}
<style>
    .card {
    }
</style>

<div class="container">
<div class="row">
    <div class="col-4 pl-5">
        <div class="mt-5">

        <img src="{{ brewery.image.url }}" height="200" width="200"/>
            </div>
    </div>
    <div class="col-8 ">

        <div class="row text-center mt-5">
            <h6>"{{ brewery.description }}"</h6>
        </div>

    </div>

    </div>

<div class="row mt-5 ml-5">
    <div class="col-6">
    <p>Brewery Name: {{ brewery.name }}</p>

    <p>Prefecture: {{ brewery.prefecture }}</p>

        <p>Address: {{ brewery.address }}</p>
        <p>Phone: {{ brewery.phone }}</p>
        <p>Email: {{ brewery.email }}</p>
        <p>Website: <a href="{{ brewery.website }}">{{ brewery.website }}</a> </p>
        </div>
<div class="col-6 mb-5 ">

<img src="{{ brewery.header.url }}" height="300" width="400"/>
</div>


</div>

</div>

    <div class="container mt-5 text-center">
<h4>Products</h4>
    <div class="card-columns mt-5">

    {% for product in products %}
    <div class="card" style="width: 20rem;">
    <div class="card-header text-center">
            <img src="{{ product.first_image.image.url }}" height="300" width="250"} />
    </div>
    <div class="card-body text-center">
        <div class="row justify-content-center"><small>{{ product.name }}</small></div>
        <div class="row justify-content-center"><small>{{ product.volume }} ml</small></div>
        <div class="row justify-content-center">
            <a href="{% url 'product' slug=product.slug %}" class="btn btn-outline-danger mb-0">More info</a>
        </div>
    </div>
    </div>

    {% endfor %}
    </div>
    </div>


{% endblock content %}

main/templates/main/order_done.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="container mt-5">
        <div class="text-center">
        <img src="{% static 'images/kanpai.jpeg' %}" width="400" height="200"/>
        </div>
        <div class="container mt-3">
        <div class="text-center">
    <h4>Thank you for your order!</h4>
            <a class="btn btn-lg btn-danger" href="{% url "product-list" 'all' %}">Continue Shopping</a>
        </div>
        </div>
</div>
{% endblock content %}

main/templates/main/order_filter.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
    <div class="container">
    <h2>Order History</h2> <form method="get">
    {{ filter.form.as_p }}
<input type="submit"/> </form>
<p>
    {% render_table filter.qs %}
</p>
    </div>
{% endblock content %}

main/templates/main/product_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <div class="row">
    <div class="col-3">
 <div  id="imagebox">
                    Loading image...

        </div>

    </div>
     <div class="col-9">
         <div class="row">
        <b> <h1><b>{{ product.name }}</b></h1></b>
             </div>
         <div class="row">
         <p>Rating:
             {% if product.average_rating  %}
             {{ product.average_rating }} out of 5 ({{ product.review_amount }} Reviews)
                 <small><a href="{% url 'add_review' product.slug  %}">Write a review!</a></small>
             {% else %}
                 <small>No reviews yet! <a href="{% url 'add_review' product.slug  %}">Would you like to write the first review?</a> </small>
             {% endif %}
         </p>&nbsp;

             </div>
         <div class="row">
         <p>{{ product.description }}</p>
             </div>
         <div class="row">
         <h4> ${{ product.price }}</h4>
             </div>
         <div class="row">
         <p> Quantity: </p>
             </div>
         <a class="btn btn-outline-danger btn-lg" href="{% url "add-to-cart" %}?product={{ object.id }}"> Add to Cart</a>



    </div>
    </div>


    </div>

<div class="container mt-5">
    <h3>Product Information</h3>
    <table class="table">
        <tr>
            <th>Brewer</th>
            <td><a href="{% url 'brewery' product.brewery.slug %}">{{ product.brewery }}</a></td>
        </tr>
        <tr>
            <th>Prefecture</th>
            <td>{{ product.brewery.prefecture }}</td>
        </tr>
        <tr>
            <th>Category</th>
            <td>{{ product.get_sake_type_display }}</td>
        </tr>
        <tr>


        </tr>
        <tr>
            <th>Volume</th>
            <td>{{ product.volume }} ml</td>
        </tr>
        <tr>
            <th>Alcohol Percentage</th>
            <td>% {{ product.abv }}</td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>{{ object.tags.all|join:", "|default:"" }}</td>
        </tr>
        <tr>
            <th>In stock</th>
            <td>{{ object.in_stock|yesno|capfirst }}</td>
        </tr>

    </table>
    </div>


{% endblock %}

{% block extra_js %}
    <script src="https://unpkg.com/react@16/umd/react.production.min.js">
    </script>
    <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js">
    </script>

    <style type="text/css" media="screen"> .image {

        margin: 0px;
        justify-content: center;
        display: inline-block;
    }
    </style>


    <script>
        const e = React.createElement;

        class ImageBox extends React.Component {
            constructor(props) {
                super(props);
                this.state = {
                    currentImage: this.props.imageStart
                }
            }

            click(image) {
                this.setState({
                    currentImage: image
                });
            }

            render() {
                const images = this.props.images.map((i) =>
                    e('div', {className: "image", key: i.id}, e('img', {
                            onClick: this.click.bind(this, i),
                            width: "75",
                            src: i.thumbnail
                        }),
                    ),
                );
                return e('div', {className: "gallery"}, e('div', {className: "current-image"},
                    e('img', {src: this.state.currentImage.image, width: 300, height:300})
                ), images)
            }
        }

        document.addEventListener("DOMContentLoaded", function (event) {
            var images = [
                {% for image in object.image_all %}
                    {
                        "image": "{{ image.image.url |safe }}",
                        "thumbnail": "{{ image.image.url|safe }}"
                    },
                {% endfor %}

            ]
            ReactDOM.render(
                e(ImageBox, {images: images, imageStart: images[0]}),
                document.getElementById('imagebox')
            );
        });

    </script>
{% endblock extra_js %}

main/templates/main/product_list.html
{% extends 'base.html' %}
{% block content %}

<style>
    .card {
        border: none;
    }


i{
    color: black;
}


</style>
<h1 class="text-center">Products</h1>
    <div class="container mt-5">

    <div class="row ml-5 mb-5">

        Sort by: &nbsp;<a href="{% url 'product-list' 'name'%}">Name</a> &nbsp;| &nbsp;
        <a href="{% url 'product-list' 'price'%}">Price</a> &nbsp;| &nbsp;
        <a href="{% url 'product-list' 'units_sold'%}"> Popularity</a>
    </div>
<div class="card">
    {% for product in object_list  %}
        <div class="row">
        <div class="col-4">

        <img src="{{ product.first_image.image.url }}" height="400" width="300"/>
        </div>
        <div class="col-8">
            <table>
                <tr>
                   <h4> {{ product.name }}</h4>
                </tr>
                <tr>
                    <p> <small>{{ product.volume }} ml </small></p>
                </tr>
                <tr>
                    <p> <small>Grade: {{ product.get_sake_type_display }}</small></p>
                </tr>
                <tr>
                   <p> Rating:</p>
                </tr>

                <tr>
                    <h5>$ {{ product.price }}</h5>
                </tr>
                <tr>
                    <p><small>Tags: {{ product.tags.all|join:", "|default:"" }}</small></p>
                </tr>
                <tr>

                    <a class="btn btn-outline-danger " href="{% url "product" product.slug %}">Check it out</a>


                </tr>

            </table>

        </div>


</div>

        {% if not forloop.last %}
            <hr/>
        {% endif %}


    {% endfor %}

    </div>
</div>

        <div class="row justify-content-center mt-5">
    <nav class="" id="pager">
        <ul class="pagination ">
            {% if page_obj.has_previous %}
                <li class="">
                    <a class="" href="?page={{ page_obj.previous_page_number }}">
                        <i class="fas fa-chevron-left  mr-3 fa-2x"></i>

                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="" href="#"><i class="fas fa-chevron-left  mr-3 fa-2x"></i></a>
                </li>
            {% endif %}
            {% for pagenum in page_obj.paginator.page_range %}
                <li class=" page-item{% if page_obj.number == pagenum %} active text-white{% endif %}">
                    <a class="page-link {% if page_obj.number == pagenum %}bg-dark {% else %}text-dark{% endif %}" href="?page={{ pagenum }}">{{ pagenum }} </a>
                </li>
            {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
            <a class="" href="?page={{ page_obj.next_page_number }}">
                <i class="fas fa-chevron-right  ml-3 fa-2x"></i>
            </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="" href="#"><i class="fas fa-chevron-right  ml-3 fa-2x"></i></a>
            </li>
        {% endif %}
        </ul>
    </nav>
        </div>




{% endblock %}