main/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.generic import TemplateView, DetailView
from .views import (ContactUsView, ProductListView, RegisterView,
    logout_user, add_to_cart, show_bestseller, BreweryListView, add_review,user_recommend_list,
    account_settings, manage_cart, remove_one_from_cart, add_one_to_cart,
    review_detail, review_list, show_brewery, UserProfileView,remove_product_from_cart, PostDetailView, PostListView)

from .models.product import Product
from main import forms, views, endpoints
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("about-us/",TemplateView.as_view(template_name="about_us.html"),name='about-us'),
    path('contact-us/', ContactUsView.as_view(),name='contact-us'),
    path('', show_bestseller,name='home'),
    path('add_to_cart/', add_to_cart, name='add-to-cart'),
    path('cart/', manage_cart, name='cart'),
    path('remove/<slug:slug>', remove_product_from_cart, name='remove-product-from-cart' ),
    path('add_one_to_cart/<slug:slug>', add_one_to_cart, name='add-one-to-cart' ),
    path('remove_one_from_cart/<slug:slug>', remove_one_from_cart, name='remove-one-from-cart' ),
    path('brewery/<slug:brewery_slug>/', show_brewery, name='brewery'),
    path('breweries/', BreweryListView.as_view(), name='breweries'),
    path('product/<slug:slug>/', DetailView.as_view(model=Product), name='product'),
    path('products/<slug:tag>/', ProductListView.as_view(), name='product-list'),
    path('register/', RegisterView.as_view(), name='register'),
    path("login/", auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name="login.html", form_class=forms.AuthenticationForm), name="login",),
    path('logout/', logout_user, name='logout'),
    path('user/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('settings/', account_settings, name='settings'),
    path(
            "address/",
            views.AddressListView.as_view(),
            name="address_list",
    ), path(
           "address/create/",
            views.AddressCreateView.as_view(),
            name="address_create",
    ), path(
           "address/<int:pk>/",
           views.AddressUpdateView.as_view(),
           name="address_update",
    ), path(
           "address/<int:pk>/delete/",
           views.AddressDeleteView.as_view(),
           name="address_delete",
    ),
    path("order/done/", TemplateView.as_view(template_name="main/order_done.html"), name="checkout_done",),
    path("order/address_select/",views.AddressSelectionView.as_view(),name="address_select",),
    path('order-dashboard', views.OrderView.as_view(), name='order_dashboard'),
    path('reviews/<int:id>', review_detail, name='review_detail'),
    path('reviews/',review_list,name='review_list'),

    path('product/<slug:slug>/add_review/', add_review, name='add_review'),
    path('recommendations/', user_recommend_list, name='user_recommend_list'),
    path('news/', PostListView.as_view(), name='news_list'),
    path('news/<int:pk>/', PostDetailView.as_view(), name='news_post'),



]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saketime_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from main import endpoints

router = routers.DefaultRouter()
router.register(r'orderlines', endpoints.PaidOrderLineViewSet)
router.register(r'orders', endpoints.PaidOrderViewSet)

"""saketime_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('main.urls')),
    path("",include('rest_framework.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models/address.py
from django.contrib.auth import get_user_model
from django.db import models


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk", "United Kingdom"),
        ("us", "United States of America"),
        ("jp", "Japan"),
        ("id", "Indonesia"),
    )

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address1 = models.CharField("Address line 1", max_length=60)
    address2 = models.CharField(
        "Address line 2", max_length=60, blank=True
    )
    zip_code = models.CharField(
        "ZIP or Postal code", max_length=12
    )
    city = models.CharField(max_length=60)
    country = models.CharField(
        max_length=3, choices=SUPPORTED_COUNTRIES
    )

    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return ", ".join(
        [
            self.name,
            self.address1,
            self.address2,
            self.zip_code,
            self.city,
            self.country,
        ])

main/models/brewery.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse
from cloudinary.models import CloudinaryField


class BreweryManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug=slug)


class Brewery(models.Model):
    name = models.CharField(max_length=250, unique=True, blank=True)
    address = models.CharField(max_length=200, blank=True)
    prefecture = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True)
    #image = models.ImageField(upload_to='breweries', blank=True)
    image = CloudinaryField('image')
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    website = models.CharField(max_length=100, blank=True)
    #header = models.ImageField(upload_to='breweries',blank=True, null=True)
    header = CloudinaryField('header')
    objects = BreweryManager()

    class Meta:
        verbose_name_plural = 'Breweries'

    def get_absolute_url(self):
        return reverse('brewery')
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Brewery, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug,)

    def get_total_sales(self):
        get_qs = self.products.all()
        total_sales = 0
        for product in get_qs:
            total_sales += product.units_sold
        return total_sales

main/forms.py
from django import forms
import logging
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.contrib.auth.forms import (
    UserCreationForm
)
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import authenticate
from django.forms import inlineformset_factory, ModelForm, Textarea
from .models import CartLine,Cart, UserProfile, Review
from . import widgets
from . import models
from cloudinary.forms import CloudinaryFileField

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, label="Your name")
    message = forms.CharField(
        max_length=600, widget=forms.Textarea
    )

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )

        send_mail(
            "Site message",
            message,
            "site@saketime.domain",
            ["customerservice@saketime.domain"],
            fail_silently=False,
        )


class RegistrationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ("email", 'username')
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
        )
        mail = "Welcome{}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to SakeTime",
            mail,
            "site@saketime.domain",
            [self.cleaned_data["email"]],
            fail_silently=True,
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(
        strip=False, widget=forms.PasswordInput
    )

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
            self.request, email=email, password=password
                )
            if self.user is None:
                raise forms.ValidationError(
                    "Invalid email/password combination."
                )
            logger.info(
                "Authentication successful for email=%s", email
            )
        return self.cleaned_data

    def get_user(self):
        return self.user


class UserProfileForm(ModelForm):
    profile_image = CloudinaryFileField(
        options={
            'folder': 'sake_time/profile_images'
        }
    )

    class Meta:
        model = UserProfile
        fields = '__all__'
        exclude = ['user']


class UserForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']
        exclude = ['user']


CartLineFormSet = inlineformset_factory(
    Cart,
    CartLine,

    fields=('quantity',),
    extra=0,
    widgets={'quantity': widgets.PlusMinusInput()}

)


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(
        queryset=None)
    shipping_address = forms.ModelChoiceField(
        queryset=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields['billing_address'].queryset = queryset
        self.fields['shipping_address'].queryset = queryset


class ReviewForm(ModelForm):

    class Meta:
        model = Review
        fields = ['rating', 'content']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 15})
        }

main/views/address.py
from django.views.generic.list import ListView
from main.models import Address
import logging
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView,UpdateView, DeleteView, FormView
from main.forms import AddressSelectionForm

# Create your views here.
logger = logging.getLogger(__name__)


class AddressListView(ListView):
    model = Address

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = Address
    fields = [
        "name",
        "address1",
        "address2",
        "zip_code",
        "city",
        "country", ]
    success_url = reverse_lazy("address_list")

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = Address
    fields = [
            "name",
            "address1",
            "address2",
            "zip_code",
            "city",
            "country",
        ]
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = Address
    success_url = reverse_lazy("address_list")

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name = 'main/address_select.html'
    form_class = AddressSelectionForm
    success_url = reverse_lazy('checkout_done')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user']= self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session['cart_id']
        cart = self.request.cart
        cart.create_order(
            form.cleaned_data['billing_address'],
            form.cleaned_data['shipping_address']
        )

        return super().form_valid(form)

main/views/brewery.py
from django.shortcuts import render, redirect, render_to_response
from main.models import Brewery, Product
from django.core.paginator import Paginator
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from django.contrib import messages

def show_brewery(request, brewery_slug):

    context = {}

    try:

        brewery = Brewery.objects.get(slug=brewery_slug)

        products = Product.objects.filter(brewery__slug=brewery_slug)

        page = request.GET.get('page', 1)
        paginator = Paginator(products, 4)
        pages= paginator.page(page)

        context['brewery'] = brewery
        context['products'] = products
        context['page_obj'] = pages

        coords = {'lat': brewery.lat, 'long': brewery.long}



    except Brewery.DoesNotExist:
        context['brewery'] = None
        messages.error(request, 'That brewery does not exist')

    return render(request, 'main/brewery_page.html', context=context)


class BreweryListView(ListView):
    template_name = "main/brewery_list.html"
    paginate_by = 5

    def get_queryset(self):
        breweries = Brewery.objects.all()

        return breweries.order_by('prefecture')

main/views/cart.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from main.models import Product, Cart, CartLine
from main.forms import CartLineFormSet
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView


def add_to_cart(request):
    product = get_object_or_404(
        Product, id=request.GET.get("product")
    )
    cart = request.cart
    if not request.cart:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        cart = Cart.objects.create(user=user)
        request.session["cart_id"] = cart.id

    cartline, created = CartLine.objects.get_or_create(
        cart=cart, product=product
    )
    if not created:
        cartline.quantity += 1
        cartline.save()
    return HttpResponseRedirect(
        reverse("product", args=(product.slug,))
    )


def manage_cart(request):

    if not request.cart:
        return render(request, 'cart.html', {'formset':None})


    if request.method == 'POST':
        formset = CartLineFormSet(
            request.POST, instance=request.cart, prefix='cartline'
        )

        if formset.is_valid():

            formset.save()
    else:
        formset = CartLineFormSet(
            instance=request.cart
        )
    if request.cart.is_empty():
        return render(request, 'cart.html', {'formset': None})
    return render(request, 'cart.html', {'formset':formset})


def add_one_to_cart(request,slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.cart
    cartline = CartLine.objects.get(cart=cart, product=product)

    if cartline:
        cartline.quantity +=1
        cartline.save()
        cart.save()

    return redirect('cart')


def remove_one_from_cart(request,slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.cart
    cartline = CartLine.objects.get(product=product, cart=cart)

    if cartline and cartline.quantity>1:
        cartline.quantity -=1
        cartline.save()
        cart.save()
    else:
        cartline.delete()
        cart.save()


    return redirect('cart')


def remove_product_from_cart(request,slug):
    product = get_object_or_404(Product, slug=slug)
    cart = request.cart
    cartline = CartLine.objects.filter(product=product, cart=cart)

    if cartline:
        cartline.delete()

    return redirect('cart')







# class CartLineDeleteView(DeleteView):
#     model = CartLine
#     success_url = reverse_lazy('cart')
#
#     def get_queryset(self):
#         return self.model.objects.filter(cart__user=self.request.user)

main/views/contact.py
from django.views.generic.edit import FormView
from main import forms
import logging
logger = logging.getLogger(__name__)


class ContactUsView(FormView):
    form_class = forms.ContactForm
    template_name = 'contact_us.html'
    success_url = '/'

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

main/templates/about_us.html
{% extends "base.html" %}
{% block content %}
<h2>About us</h2>
{% endblock content %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6b38a7ee17.js" crossorigin="anonymous"></script>

    <style>
        #page-container {
  position: relative;
  min-height: 30vh;
}
#content-wrap {
  padding-bottom: 2.5rem;
}
        #footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  height: 2.5rem;
}
    </style>
    <title>SakeTime</title>
    {% include 'navbar.html' %}


    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}

{% block content %}


{% endblock content %}
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
{% block extra_js %}
{% endblock extra_js %}
<div id="page-container">
   <div id="content-wrap">
     <!-- all other page content -->
   </div>
    <footer id="footer">
        {% include 'footer.html' %}
    </footer>
 </div>
</body>
</html>

main/templates/cart.html
{% extends "base.html" %}
{% load static %}
<style>
    img {
        margin-right: 100vh;
    }
    </style>
{% block content %}
    {% if formset %}

        <div class="container">

    <form method="POST">
        {% csrf_token %}
    <div class="table-responsive">
    <h2 class="mb-3">Your Cart</h2>
    <table class="table">
        <thead>
        <tr>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Price</th>
        <th scope="col" class="text-right"></th>
        </tr>
        </thead>
    <tbody>
    {{ cartline.management_form }}
    {% for form in formset %}
        <tr>
                <td>
                    <div class="row">
                    <div class="col-2 mr-auto">

                    <img class="img-sm img-responsive" src="{{ form.instance.product.first_image.image.url }} " height="100" width="50"/>
                    </div>

                    <div class="col-10">
                    <h6><a href="{{ form.instance.product.get_absolute_url }}">{{ form.instance.product.name }}</a> </h6>
                        <p><small>{{ form.instance.product.volume }} ml</small></p>
                        </div>
                    </div>
                </td>
        <td>$ {{ form.instance.product.price }}</td>
            <td id="quantity"><a href="{% url 'remove-one-from-cart' slug=form.instance.product.slug  %}"><i class="fas fa-minus-circle mr-2"></i></a>{{ form.instance.quantity }}<a href="{% url 'add-one-to-cart' slug=form.instance.product.slug  %}"><i class="fas fa-plus-circle ml-2"></i></a></td>
        <td id="price">$ {{ form.instance.get_total_price }}</td>
        <td><a href="{% url 'remove-product-from-cart' slug=form.instance.product.slug %}"><i class="fas fa-trash float-right" style="color: Red;"></i></a></td>
        </tr>
        {% endfor %}
    <tr>
        <td>Order Total</td>
        <td></td>
        <td>{{ request.cart.count }}</td>
        <td colspan="2">$ {{ request.cart.get_total }}</td>
    </tr>

        </tbody>



         </table>

        <!-- table-responsive-->
         </div>
    </form>
        </div>
        <div class="container">

            {% if user.is_authenticated %}

            <div class="text-right">
            <a href="{% url "product-list" 'all' %}" class="btn btn-lg btn-danger">Continue Shopping</a>
         <a href="{% url "address_select" %}" class="btn btn-lg btn-danger">Place order</a>
                </div>

{% else %}
                <div class="text-right">

         <a href="{% url "login" %}?next={% url "address_select" %}"
class="btn btn-danger btn-lg">Login</a>
                <a href="{% url "register" %}?next={% url "address_select" %}" class="btn btn-lg btn-danger">Signup</a>
                </div>

     {% endif %}
        <!-- container-->
        </div>

{% else  %}
        <div class="container mt-5">
        <div class="text-center">
        <img src="{% static 'images/emptycart.jpg' %}" width="200" height="200"/>
        </div>
        <div class="container mt-3">
        <div class="text-center">
    <h4>Your cart is empty</h4>
            <h6>We can help with that!</h6>
            <a class="btn btn-lg btn-danger" href="{% url "product-list" 'all' %}">Start Shopping</a>
        </div>
        </div>
</div>

{% endif %}
{% endblock content %}

main/templates/contact_us.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">

        <div class="row wow fadeIn">
            <div class="col-6 offset-3">
                <h5 class="my-5 h2 text-center">Contact us</h5>
                <form method="POST">
                    {% csrf_token %}
                    <p class="mx-auto text-center">Your name</p>

                    <div class="form-group">

                        <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                               id="id_name"
                               name="name"
                               value="{{ form.name.value|default:"" }}">
                        {% if form.name.errors %}
                            <div class="invalid-feedback">
                                {{ form.name.errors }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <p class="mx-auto text-center"> Message</p> <textarea class="form-control {% if form.message.errors %}
      is-invalid{% endif %}"
                                                               id="id_message"
                                                               name="message"
                                                               rows="3">
      {{ form.message.value|default:"" }}
</textarea>
                        {% if form.message.errors %}
                            <div class="invalid-feedback">
                                {{ form.message.errors }}
                            </div>
                        {% endif %}
                    </div>
                <div class="form-row col-12 text-center">
                    <div class="col-12">
                    <button type="submit"  class="btn  btn-danger">Submit</button>
                    </div>
                </div>
                </form>
            </div>
        </div>

    </div>

{% endblock content %}

main/templates/login.html
{% load static %}

    <link rel="stylesheet" href="{% static 'css/login.css'  %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>


<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
        <div class="text-center">
        <img  src="{% static 'images/sakecups.jpeg' %}">


              <h3 class="login-heading mb-4">Welcome back!</h3>
        </div>
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">



              <form method="post">
                  {% csrf_token %}
                  {{ form.non_field_errors }}

            <div class="form-label-group">

                <input id="id_email" value="{{ form.email.value|default:"" }}" type="email"
                       class="form-control  {% if form.email.errors %} is-invalid{% endif %}"
                       aria-describedby="emailHelp"
                       placeholder="Enter email" name="email">
            <label for="id_email">Email address</label>
                {% if form.email.errors %}
                    <div class="invalid-feedback">
                        {{ form.email.errors }}
                    </div>
                {% endif %}
            </div>

            <div class="form-label-group">

                <input type="password" class="form-control {% if form.password.errors %} is-invalid{% endif %}"
                       id="id_password" name="password" placeholder="Password"
                       value="{{ form.password.value|default:"" }}">
            <label for="id_password">Password</label>
                {% if form.password.errors %}
                    <div class="invalid-feedback">
                        {{ form.password.errors }}
                    </div>
                {% endif %}
            </div>



{#                <div class="custom-control custom-checkbox mb-3">#}
{#                  <input type="checkbox" class="custom-control-input" id="customCheck1">#}
{#                  <label class="custom-control-label" for="customCheck1">Remember password</label>#}
{#                </div>#}
                <button class="btn btn-lg btn-danger btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign in</button>
{#                <div class="text-center">#}
{#                  <a class="small" href="#">Forgot password?</a></div>#}
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

main/templates/register.html
{% load static %}
{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/register.css'  %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
{% endblock extra_head %}

<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
        <div class="text-center">
                <h2 >Register</h2>
            <img  src="{% static 'images/masu.jpeg' %}">
            </div>
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">

              <form method="post">
                  {% csrf_token %}
                  {{ form.non_field_errors }}
               <div class="form-label-group">

                <input id="id_username" value="{{ form.username.value|default:"" }}" type="text"
                       class="form-control"

                       placeholder="Enter username" name="username">
            <label for="id_username">Username</label>

            </div>
            <div class="form-label-group">

                <input id="id_email" value="{{ form.email.value|default:"" }}" type="email"
                       class="form-control  {% if form.email.errors %} is-invalid{% endif %}"
                       aria-describedby="emailHelp"
                       placeholder="Enter email" name="email">
            <label for="id_email">Email address</label>
                {% if form.email.errors %}
                    <div class="invalid-feedback">
                        {{ form.email.errors }}
                    </div>
                {% endif %}
            </div>

              <hr/>

            <div class="form-label-group">

                <input type="password" class="form-control {% if form.password1.errors %} is-invalid{% endif %}"
                       id="id_password1" name="password1" placeholder="Password"
                       value="{{ form.password1.value|default:"" }}">
            <label for="id_password1">Password</label>
                {% if form.password.errors %}
                    <div class="invalid-feedback">
                        {{ form.password1.errors }}
                    </div>
                {% endif %}
            </div>

               <div class="form-label-group">
                <input type="password" class="form-control {% if form.password2.errors %} is-invalid{% endif %}"
                       id="id_password2" name="password2" placeholder="Password"
                       value="{{ form.password2.value|default:"" }}">
            <label for="id_password2">Confirm Password</label>
            </div>

                <button class="btn btn-lg btn-danger btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign Up</button>
              <a class="d-block text-center mt-2 small" href="{% url 'login' %}">Already have an account? Click here to sign in.</a>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>